import sys, os, subprocess, glob, uuid, shutil, threading, json
from flask import Flask, jsonify, request, send_from_directory, render_template

app = Flask(__name__)

# CONFIG
CORE_PATH = "/core"
BASE_DATA_PATH = "/data"
USER_DATA_PATH = os.path.join(BASE_DATA_PATH, "users")
generation_lock = threading.Lock()

os.makedirs(os.path.join(BASE_DATA_PATH, "seeds"), exist_ok=True)
os.makedirs(USER_DATA_PATH, exist_ok=True)

@app.route('/')
def home(): return render_template('index.html')
@app.route('/generator')
def generator_page(): return render_template('generator.html')
@app.route('/api/download/<filename>')
def download_file(filename): return send_from_directory(os.path.join(BASE_DATA_PATH, "seeds"), filename, as_attachment=True)

# GESTION UTILISATEUR & UPLOAD (Identique à avant)
@app.route('/api/user/status', methods=['POST'])
def check_user_status():
    uid = request.get_json().get('user_id')
    u_dir = os.path.join(USER_DATA_PATH, uid) if uid else ""
    if not uid or not os.path.exists(u_dir): return jsonify({"emerald": False, "frlg": False})
    return jsonify({
        "emerald": os.path.exists(os.path.join(u_dir, "Pokemon Emerald.gba")),
        "frlg": os.path.exists(os.path.join(u_dir, "Pokemon FireRed.gba"))
    })

@app.route('/api/user/upload', methods=['POST'])
def upload_roms():
    uid = request.form.get('user_id')
    u_dir = os.path.join(USER_DATA_PATH, uid)
    os.makedirs(u_dir, exist_ok=True)
    mapping = {'rom_emerald': 'Pokemon Emerald.gba', 'rom_frlg': 'Pokemon FireRed.gba'}
    for key, val in mapping.items():
        f = request.files.get(key)
        if f: f.save(os.path.join(u_dir, val))
    return jsonify({"status": "Success"})

# CONVERSION JSON -> YAML
def build_yaml(name, game, options):
    lines = [f"name: {name}", f"game: {game}", f"description: Generated by Celio", f"{game}:"]
    # Valeurs par défaut obligatoires
    defaults = {"progression_balancing": 50, "accessibility": "locations", "death_link": "false"}
    full_opts = {**defaults, **options}

    for k, v in full_opts.items():
        # Conversion des types pour Archipelago
        if v in ["true", "True", True]: val = "true"
        elif v in ["false", "False", False]: val = "false"
        elif str(v).isdigit(): val = int(v) # Garder les nombres comme nombres
        else: val = v
        
        lines.append(f"  {k}: {val}")
    return "\n".join(lines)

@app.route('/api/generate', methods=['POST'])
def generate_seed():
    if generation_lock.locked(): return jsonify({"error": "Busy"}), 503
    data = request.get_json()
    uid = data.get('user_id')
    config = data.get('config')
    
    u_dir = os.path.join(USER_DATA_PATH, uid)
    if not os.path.exists(os.path.join(u_dir, "Pokemon Emerald.gba")): return jsonify({"error": "ROMs manquantes"}), 404

    job_id = str(uuid.uuid4())
    job_dir = os.path.join(BASE_DATA_PATH, "yamls", job_id)
    out_dir = os.path.join(BASE_DATA_PATH, "seeds", job_id)
    os.makedirs(job_dir, exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    try:
        with generation_lock:
            # Création YAML Emerald
            with open(os.path.join(job_dir, "P1.yaml"), 'w') as f:
                f.write(build_yaml(config['emerald']['name'], "Pokemon Emerald", config['emerald']['options']))
            
            # Création YAML FRLG
            with open(os.path.join(job_dir, "P2.yaml"), 'w') as f:
                f.write(build_yaml(config['frlg']['name'], "Pokemon FireRed and LeafGreen", config['frlg']['options']))

            # Copie des ROMs
            shutil.copy(os.path.join(u_dir, "Pokemon Emerald.gba"), os.path.join(CORE_PATH, "Pokemon Emerald.gba"))
            shutil.copy(os.path.join(u_dir, "Pokemon FireRed.gba"), os.path.join(CORE_PATH, "Pokemon FireRed.gba"))

            # Lancement
            cmd = ["python3", "Generate.py", "--player_files_path", job_dir, "--outputpath", out_dir, "--spoiler", "0"]
            proc = subprocess.run(cmd, capture_output=True, text=True, cwd=CORE_PATH)

            # Nettoyage ROMs
            if os.path.exists(os.path.join(CORE_PATH, "Pokemon Emerald.gba")): os.remove(os.path.join(CORE_PATH, "Pokemon Emerald.gba"))
            if os.path.exists(os.path.join(CORE_PATH, "Pokemon FireRed.gba")): os.remove(os.path.join(CORE_PATH, "Pokemon FireRed.gba"))

            if proc.returncode != 0: raise Exception(proc.stderr)
            
            zips = glob.glob(os.path.join(out_dir, '*.zip'))
            if not zips: raise Exception(proc.stdout[-500:])
            
            final_name = os.path.splitext(os.path.basename(zips[0]))[0] + ".celio"
            shutil.move(zips[0], os.path.join(BASE_DATA_PATH, "seeds", final_name))
            shutil.rmtree(job_dir)
            shutil.rmtree(out_dir)

            return jsonify({"status": "Success", "download_url": f"/api/download/{final_name}"})
            
    except Exception as e:
        shutil.rmtree(job_dir, ignore_errors=True)
        shutil.rmtree(out_dir, ignore_errors=True)
        return jsonify({"status": "Failure", "error": str(e)}), 500

if __name__ == '__main__': app.run(host='0.0.0.0', port=5000)